require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Hello_ReactNative' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  pod 'Reveal-SDK','21', :configurations => ['Debug'] #Reveal21 使用
  
  target 'Hello_ReactNativeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Hello_ReactNative-tvOS' do
  # Pods for Hello_ReactNative-tvOS

  target 'Hello_ReactNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
